---
language: ruby
before_script: "gem install --no-ri --no-rdoc bundler"
script: "bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation' "
env:
  - PUPPET_GEM_VERSION="~> 3.7"
rvm:
 - 2.0.0
notifications:
  email: false
gemfile: Gemfile
