---
language: ruby
script: "SPEC_OPTS='--format documentation' bundle exec rake spec"
env:
  - PUPPET_GEM_VERSION="~> 3.7"
notifications:
  email: false
rvm:
  - 2.0.0
before_script: "gem install --no-ri --no-rdoc bundler"
gemfile: Gemfile
